Software_Chasers_SISAPP/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sisapp.urls'))
]

sisapp/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic import RedirectView
from django.views.static import serve

import sisapp.views
from sisapp.Views import studentViews, courseViews, departmentViews, instructorViews, registrationViews, studyTermViews, \
    teachingAssignmentsViews

app_name = 'sisapp'

urlpatterns = [

                  # /Course urls

                  path('course/create', courseViews.CourseCreate.as_view(template_name='course/course_create.html'),
                       name='course_create'),
                  path('course/list', courseViews.CourseListView.as_view(template_name='course/course_list.html'),
                       name='course_list'),
                  path('course/details/<pk>',
                       courseViews.CourseDetailView.as_view(template_name='course/course_list_item.html'),
                       name='course_details'),
                  path('course/edit/<pk>',
                       courseViews.CourseUpdateView.as_view(template_name='course/course_edit.html'),
                       name='course_edit'),
                  path('course/delete/<pk>',
                       courseViews.CourseDeleteView.as_view(template_name='course/course_delete.html'),
                       name='course_delete'),

                  #  /Department urls

                  path('department/create',
                       departmentViews.DepartmentCreate.as_view(template_name='department/department_create.html'),
                       name='department_create'),
                  path('department/list',
                       departmentViews.DepartmentListView.as_view(template_name='department/department_list.html'),
                       name='department_list'),
                  path('department/details/<pk>',
                       departmentViews.DepartmentDetailView.as_view(
                           template_name='department/department_list_item.html'),
                       name='department_details'),
                  path('department/edit/<pk>',
                       departmentViews.DepartmentUpdateView.as_view(template_name='department/department_edit.html'),
                       name='department_edit'),
                  path('department/delete/<pk>',
                       departmentViews.DepartmentDeleteView.as_view(template_name='department/department_delete.html'),
                       name='department_delete'),

                  # Instructor Urls
                  path('instructor/create',
                       instructorViews.InstructorCreate.as_view(template_name='instructor/instructor_create.html'),
                       name='instructor_create'),
                  path('instructor/list',
                       instructorViews.InstructorListView.as_view(template_name='instructor/instructor_list.html'),
                       name='instructor_list'),
                  path('instructor/details/<pk>',
                       instructorViews.InstructorDetailView.as_view(template_name='instructor'
                                                                                  '/instructor_list_item.html'),
                       name='instructor_details'),
                  path('instructor/edit/<pk>',
                       instructorViews.InstructorUpdateView.as_view(template_name='instructor/instructor_edit.html'),
                       name='instructor_edit'),
                  path('instructor/delete/<pk>',
                       instructorViews.InstructorDeleteView.as_view(template_name='instructor/instructor_delete.html'),
                       name='instructor_delete'),

                  # Registration Urls

                  path('registration/create',
                       registrationViews.RegistrationCreate.as_view(
                           template_name='registration/registration_create.html'),
                       name='registration_create'),
                  path('registration/list',
                       registrationViews.RegistrationListView.as_view(
                           template_name='registration/registration_list.html'),
                       name='registration_list'),
                  path('registration/details/<pk>',
                       registrationViews.RegistrationDetailView.as_view(template_name='registration'
                                                                                      '/registration_list_item.html'),
                       name='registration_details'),
                  path('registration/edit/<pk>',
                       registrationViews.RegistrationUpdateView.as_view(
                           template_name='registration/registration_edit.html'),
                       name='registration_edit'),
                  path('registration/delete/<pk>',
                       registrationViews.RegistrationDeleteView.as_view(
                           template_name='registration/registration_delete.html'),
                       name='registration_delete'),

                  # Student urls
                  path('student/create',
                       studentViews.StudentCreate.as_view(template_name='student/student_create.html'),
                       name='student_create'),
                  path('student/list',
                       studentViews.StudentListView.as_view(template_name='student/student_list.html'),
                       name='student_list'),
                  path('student/details/<pk>', studentViews.StudentDetailView.as_view(template_name='student'
                                                                                                    '/student_list_item.html'),
                       name='student_details'),
                  path('student/edit/<pk>',
                       studentViews.StudentUpdateView.as_view(template_name='student/student_edit.html'),
                       name='student_edit'),
                  path('student/delete/<pk>',
                       studentViews.StudentDeleteView.as_view(template_name='student/student_delete.html'),
                       name='student_delete'),

                  # study Term
                  path('studyterm/create',
                       studyTermViews.StudyTermCreate.as_view(template_name='studyTerm/studyTerm_create.html'),
                       name='studyTerm_create'),
                  path('studyterm/list',
                       studyTermViews.StudyTermListView.as_view(template_name='studyTerm/studyTerm_list.html'),
                       name='studyTerm_list'),
                  path('studyterm/details/<pk>',
                       studyTermViews.StudyTermDetailView.as_view(template_name='studyTerm/studyTerm_list_item.html'),
                       name='studyTerm_details'),
                  path('studyterm/edit/<pk>',
                       studyTermViews.StudyTermUpdateView.as_view(template_name='studyTerm/studyTerm_edit.html'),
                       name='studyTerm_edit'),
                  path('studyterm/delete/<pk>',
                       studyTermViews.StudyTermDeleteView.as_view(template_name='studyTerm/studyTerm_delete.html'),
                       name='studyTerm_delete'),

                  # TeachingAssignment
                  path('teachingassignments/create', teachingAssignmentsViews.TeachingAssignmentCreate.as_view(
                      template_name='teachingAssignment/teachingAssignment_create.html'),
                       name='teachingAssignments_create'),
                  path('teachingassignments/list',
                       teachingAssignmentsViews.TeachingAssignmentsListView.as_view(
                           template_name='teachingAssignment/teachingAssignment_list.html'),
                       name='teachingAssignments_list'),
                  path('teachingassignments/details/<pk>',
                       teachingAssignmentsViews.TeachingAssignmentsDetailView.as_view(
                           template_name='teachingAssignment/teachingAssignment_list_item.html'),
                       name='teachingAssignments_details'),
                  path('teachingassignments/edit/<pk>',
                       teachingAssignmentsViews.TeachingAssignmentsUpdateView.as_view(
                           template_name='teachingAssignment/teachingAssignment_edit.html'),
                       name='teachingAssignments_edit'),
                  path('teachingassignments/delete/<pk>',
                       teachingAssignmentsViews.TeachingAssignmentsDeleteView.as_view(
                           template_name='teachingAssignment/teachingAssignment_delete.html'),
                       name='teachingAssignments_delete'),

                  path("", sisapp.views.index, name='index'),
                  path('about', sisapp.views.about, name='about'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends 'base.html' %}
{% block title_block %}
About
{% endblock %}
{% block body_block %}

<table class="table table-hover">
<center>
    <thead>
        <tr>
            <th colspan="1" scope="col">Team SoftwareChasers</th>
        </tr>
    </thead>
    <tbody>
    {% for name in data %}
        <tr><td>{{ name }}</td></tr>
    {% endfor %}
    </tbody>
    </center>

</table>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon"  href="{% static 'img/img.ico' %}"/>

    <!-- Bootstrap CSS -->
  <style>
       td,th {
           background: #CDF5F6;
       }
       body {
          min-height: 80vh;
   height: auto !important;
   height: 100%;
   margin: 0 auto -60px;
        }

  </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <title> {% block title_block %}
        {% endblock %}
    </title>
  </head>
  <body style="background-image: url({% static 'img/bg4.webp' %}) ;background-size: cover ">
{#  <body style="background: #FFD670">#}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'sisapp:index' %}">Student Information System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {#Student#}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sisapp:student_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Student
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sisapp:student_create' %}">Add Student</a>
              <a class="dropdown-item" href="{% url 'sisapp:student_list' %}">List Students</a>
            </div>
          </li>

{#          Instructor#}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sisapp:student_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Instructor
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sisapp:instructor_create' %}">Add Instructor</a>
              <a class="dropdown-item" href="{% url 'sisapp:instructor_list' %}">List Instructors</a>
            </div>
          </li>

{#          Departments #}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sisapp:student_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Departments
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sisapp:department_create' %}">Add Department </a>
              <a class="dropdown-item" href="{% url 'sisapp:department_list' %}">List Department</a>
            </div>

{#          Courses#}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sisapp:student_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Courses
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sisapp:course_create' %}">Add Courses </a>
              <a class="dropdown-item" href="{% url 'sisapp:course_list' %}">List Courses</a>
            </div>
          </li>

{#          Study Terms #}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sisapp:student_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Study Terms
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sisapp:studyTerm_create' %}">Add Term </a>
              <a class="dropdown-item" href="{% url 'sisapp:studyTerm_list' %}">List Term</a>
            </div>
          </li>
  {#          Teaching Assignment #}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sisapp:student_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Teaching Assignment
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sisapp:teachingAssignments_create' %}">Assign Teacher </a>
              <a class="dropdown-item" href="{% url 'sisapp:teachingAssignments_list' %}">List Assignment</a>
            </div>
          </li>

{#          Course Resistration #}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'sisapp:student_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Course Resistration
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sisapp:registration_create' %}">Register Course</a>
              <a class="dropdown-item" href="{% url 'sisapp:registration_list' %}">List Registered Courses</a>
            </div>
          </li>
          <li class="nav-item">
        <a class="dropdown-item" href="{% url 'sisapp:about' %}">About</a>
      </li>
      </ul>
  </div>
</nav>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% block body_block %}
  {% endblock %}

<footer class="footer fixed-bottom" style="position:relative; width:100%;">
      <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2021 - Software Chasers SIS Application
  </div>
  </footer>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}
    Home Page
{% endblock %}
{% block body_block %}
    <div>
    <div class="py-5">
    <div class="container" >
      <div class="row hidden-md-up">
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">Students</h4>
              <h6 class="card-subtitle text-muted">Students Basic Information</h6>
              <a href="{% url 'sisapp:student_create' %}" class="card-link">Register here</a>
              <a href="{% url 'sisapp:student_list' %}" class="card-link"> View Registered Students</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">Instructor</h4>
              <h6 class="card-subtitle text-muted">Instructor Basic Information</h6>
              <a href="{% url 'sisapp:instructor_create' %}" class="card-link">Register here</a>
              <a href="{% url 'sisapp:instructor_list' %}" class="card-link"> View Instructors</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">Courses Register</h4>
              <h6 class="card-subtitle text-muted">Course Registration information</h6>
              <a href="{% url 'sisapp:student_create' %}" class="card-link">Enroll for Courses</a>
              <a href="{% url 'sisapp:student_list' %}" class="card-link"> Enrolled Courses</a>
            </div>
          </div>
        </div>
      </div><br>
      <div class="row">
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">Department</h4>
              <h6 class="card-subtitle text-muted">Department Basic Information</h6>
              <a href="{% url 'sisapp:department_create' %}" class="card-link">Add Department here</a>
              <a href="{% url 'sisapp:department_list' %}" class="card-link">Departments present</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">Courses</h4>
              <h6 class="card-subtitle text-muted">Course Information</h6>
              <a href="{% url 'sisapp:course_create' %}" class="card-link">Add Courses here</a>
              <a href="{% url 'sisapp:course_list' %}" class="card-link"> View Available Courses</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">Study Term</h4>
              <h6 class="card-subtitle text-muted">Terms Information</h6>
              <a href="{% url 'sisapp:student_create' %}" class="card-link">Add Term</a>
              <a href="{% url 'sisapp:studyTerm_list' %}" class="card-link">View Available Terms</a>
            </div>
          </div>
        </div>
      </div>
        <br/>
        <div class="row">
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">Teaching Assignment</h4>
              <h6 class="card-subtitle text-muted">Teaching Assignment Information</h6>
              <a href="{% url 'sisapp:teachingAssignments_create' %}" class="card-link">Add Teaching Assignment here</a>
              <a href="{% url 'sisapp:teachingAssignments_list' %}" class="card-link">Teaching Assignments</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card">
            <div class="card-block" style="height: 100px;border-style: outset">
              <h4 class="card-title">About</h4>
              <h6 class="card-subtitle text-muted">Team Information</h6>
              <a href="{% url 'sisapp:about' %}" class="card-link">View Team Members here</a>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
    </div>
{% endblock %}